### ISSUE TITLE
snapshot: use correct language-specific comment token for snapshot output

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/scip#111]
Noticed when trying out scip-ruby that the snapshot output uses `//` regardless of language, which is the wrong comment token for ruby. This used to be a thing in the old snapshot code in scip-java I believe, so itd be cool to reintroduce it here.

**Comment by varungandhi-src** [comment]
Yeah, I was going to make it customizable, but we didn't change it because this is mostly used for debugging. The snapshot code in scip-ruby uses `#`, and it is ported from the code here but tailored a bit so that we can evolve it independently (and avoids a dependency on a Go project from a C++ project).
