### ISSUE TITLE
SCIP files for Data flow

### ISSUE THREAD

**Issue by chrisrickard** [sourcegraph/scip#227]
Hey team, I'm not 100% SCIP is the solution here, but I'm looking to understand the data flow through a code base, e.g. starting with a button click, what other files and methods are called - essentially following it through the entire data flow lifecycle from file to file.

I was interested in SCIP files, and was wondering with the information contained in them - do you think this is possible?

**Comment by varungandhi-src** [comment]
What you're describing is a call hierarchy like feature, that is supported by various IDEs like IntelliJ.

For this, SCIP's `enclosing_range` property is useful. In pseudocode:

```
   if occ1.symbolRole == SymbolRole.Reference && occ2.symbolRole == SymbolRole.Definition
      && occ2.enclosing_range.contains(occ1.range) {
    callsSet.insert((occ1.symbol, occ2.symbol))
  }
```

As of right now, most Sourcegraph-maintained SCIP indexers do not emit the `enclosing_range` property, since the indexers were written before this property was added to SCIP. The exception is `scip-python`, where support for it was added recently by a non-Sourcegraph contributor. https://github.com/sourcegraph/scip-python/pull/132

For other indexers, if you'd like to add support for this property, you can open a PR and ping me (or `@keynmol` for scip-java) for review.

Does that answer your question?

**Comment by chrisrickard** [comment]
It does - thank you :)
